# Dependabot version updates.
# Docs: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      nuget-minor-and-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
