<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="LibGit2Sharp" />
        <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Core\PublicTxt.Core\PublicTxt.Core.csproj" />
    </ItemGroup>

</Project>
