<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="LibGit2Sharp" Version="0.32.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Core\PublicTxt.Core\PublicTxt.Core.csproj" />
    </ItemGroup>

</Project>
